# Generated by Django 2.0.7 on 2018-09-22 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(editable=False, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('vendor', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('engine_identifier', models.CharField(max_length=20, unique=True)),
                ('mileage', models.IntegerField()),
            ],
            options={
                'ordering': ('vendor', 'model'),
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(editable=False, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'engine'), (1, 'body'), (2, 'electrical'), (4, 'chassis')], default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
            options={
                'ordering': ('car', 'type'),
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
            options={
                'ordering': ('start_date', 'end_date', 'distance'),
            },
        ),
    ]
