# Generated by Django 2.0.7 on 2018-09-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20180922_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car', to_field='uid'),
        ),
    ]
