version: '3.7'

services:
  web:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: gunicorn --bind ${APP_HOST}:${APP_PORT} app:app
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

volumes:
    db_data:

