version: '3.6'

services:
  db:
    restart: always
    image: postgres:10.4-alpine
    ports:
      - "5433:5433"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - ../old_django_test_tasks/tests_django/.env
  web:
    restart: always
    build: .
    command: python ../old_django_test_tasks/manage.py migrate --noinput
    command: python ../old_django_test_tasks/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../old_django_test_tasks:/old_django_test_tasks
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ../old_django_test_tasks/tests_django/.env