# Generated by Django 2.0.4 on 2018-06-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playschool', '0002_auto_20180627_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='has_come_with',
            new_name='has_came_with',
        ),
    ]
