# Generated by Django 2.0.4 on 2018-05-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_sizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='download_url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='size',
            name='download_url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='image_sizer.Image'),
        ),
    ]
