# Generated by Django 2.0.4 on 2018-05-02 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_sizer', '0002_auto_20180502_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('download_url', models.URLField(null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='size',
            name='image',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='resize',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resizes', to='image_sizer.Image'),
        ),
    ]
