# Generated by Django 2.0.4 on 2018-05-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_sizer', '0003_auto_20180502_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='format',
        ),
        migrations.AlterField(
            model_name='resize',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resize',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
