# Generated by Django 2.0.4 on 2018-05-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_sizer', '0007_remove_image_jpeg_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='download_url',
            field=models.URLField(null=True),
        ),
    ]
