# Generated by Django 2.0.4 on 2018-05-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_sizer', '0008_auto_20180511_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='download_url',
            new_name='download',
        ),
        migrations.RemoveField(
            model_name='resize',
            name='file',
        ),
        migrations.AddField(
            model_name='resize',
            name='resize_file',
            field=models.ImageField(null=True, upload_to='uploads/resizes/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(null=True, upload_to='uploads/images/'),
        ),
    ]
