# Generated by Django 2.1.1 on 2019-01-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4, unique=True)),
                ('is_provided', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
