# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_tag', '0005_auto_20171128_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['slug'], 'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
    ]
