# Generated by Django 2.1.1 on 2020-07-31 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to='image_sizer/images/%Y/%m/%d')),
                ('download', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('resize_file', models.ImageField(null=True, upload_to='resizes/%Y/%m/%d')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resizes', to='image_sizer.Image')),
            ],
        ),
    ]
