# Generated by Django 2.0.1 on 2018-02-26 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20180226_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)], verbose_name='ИНН'),
        ),
    ]
