# Generated by Django 5.1 on 2024-08-21 06:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тарифа', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('product', models.ForeignKey(help_text='Продукт', on_delete=django.db.models.deletion.CASCADE, to='easy_xml.product')),
            ],
            options={
                'ordering': ['name', '-price'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название акции', max_length=255)),
                ('discount', models.IntegerField(help_text='Процент скидки', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start_at', models.DateField(help_text='Дата начала акции')),
                ('end_at', models.DateField(help_text='Дата завершения акции')),
                ('tariffs', models.ManyToManyField(to='easy_xml.tariff')),
            ],
            options={
                'ordering': ['name', '-discount'],
            },
        ),
    ]
