# Generated by Django 2.0.4 on 2018-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_sizer', '0005_auto_20180507_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resize',
            name='download_url',
        ),
        migrations.AddField(
            model_name='resize',
            name='file',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
