version: '3.7'

services:
  web:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: gunicorn --bind ${APP_HOST}:${APP_PORT} app:app
    depends_on:
      - celery
      - postgres
  
  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    command: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    hostname: redis

  celery:
    build: ./app
    env_file:
      - .env
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - redis

  celery_beat:
    build: ./app
    env_file:
      - .env
    command: celery -A app.celery beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
      - celery
    volumes:
      - ./app/:/usr/src/app/


  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

volumes:
    db_data:
  