# Generated by Django 2.0.7 on 2018-09-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='fluffiness',
            field=models.IntegerField(choices=[(0, 'No fur'), (1, 'Short-haired'), (2, 'Medium-haired'), (4, 'Fluffy')], default=2),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
