"""init

Revision ID: 6c3b8a8c5742
Revises: 
Create Date: 2023-02-11 19:14:16.169108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3b8a8c5742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_phone_number', table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###
