# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('rotation_started', models.DateField(editable=False)),
                ('rotation_ended', models.DateField(editable=False)),
                ('applicaton_name', models.CharField(max_length=255)),
                ('application_type', models.PositiveSmallIntegerField(choices=[(0, 'Customer'), (1, 'Mortgage'), (2, 'Car'), (3, 'Business')], default=0)),
                ('score_min', models.PositiveSmallIntegerField()),
                ('score_max', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('passport', models.CharField(max_length=255)),
                ('score', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('submitted', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Sent')], default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Application')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Questionnaire')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
