# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-created',), 'verbose_name': 'Предложение по кредиту', 'verbose_name_plural': 'Предложения по кредитам'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ('-created',), 'verbose_name': 'Анкета клиента', 'verbose_name_plural': 'Анкеты клиентов'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created',), 'verbose_name': 'Заявка на кредит', 'verbose_name_plural': 'Заявки на кредиты'},
        ),
        migrations.AlterField(
            model_name='application',
            name='rotation_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='rotation_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='score_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='score_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
