# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 10:04
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_groups(apps, schema_editor):

    superusers = Group.objects.create(name='Суперпользователи')
    partners = Group.objects.create(name='Партнёры')
    banks = Group.objects.create(name='Банки')

    perm_add_questionnaire = Permission.objects.get(
        codename='add_questionnaire')
    perm_edit_questionnaire = Permission.objects.get(
        codename='change_questionnaire')
    perm_delete_questionnaire = Permission.objects.get(
        codename='change_questionnaire')

    superusers.permissions.add(perm_add_questionnaire)
    superusers.permissions.add(perm_edit_questionnaire)
    superusers.permissions.add(perm_delete_questionnaire)


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
